source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.4'

gem 'rails-api'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

gem 'rainbows', '4.4.3'

gem 'firehose'

group :development, :test do
  gem 'rspec-rails'
  # Factory Girl gem for testing
  gem 'factory_girl_rails'
  gem 'capybara'
  # Guard automatically runs rspec tests with file save
  gem 'guard-rspec'
  # On mac it gives you growl notifications in the corner
  gem 'growl'
  # seed dump allows us to dump our DB data to the db/seeds.rb file
  gem 'seed_dump'
  #for selenium testing
  gem 'selenium-webdriver'
  gem 'selenium-client'

end
